services:
  db:
    build: ./db
    restart: always
    environment:
      POSTGRES_DB: vitrine
      POSTGRES_PASSWORD: password_db
      POSTGRES_INITDB_ARGS: --encoding=UTF8 --locale=pt_BR.UTF-8 --locale-provider=libc
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build: ./app
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - db

volumes:
  db_data:
